// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpeedtestDashboard.Infrastructure.Persistence;

#nullable disable

namespace SpeedtestDashboard.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DashboardDbContext))]
    [Migration("20260905081900_RemoveIperfRequestFields")]
    partial class RemoveIperfRequestFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("SpeedtestDashboard.Infrastructure.Persistence.Entities.SpeedTestJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedServerId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SpeedTestJobs", (string)null);
                });

            modelBuilder.Entity("SpeedtestDashboard.Infrastructure.Persistence.Entities.SpeedTestResultEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DownloadMbps")
                        .HasColumnType("REAL");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("IPv4Address")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("IPv4AddressSource")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("IPv4AsName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("IPv4Asn")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("IPv4City")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("IPv4CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("IPv4CountryName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("IPv4Isp")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("IPv4MetadataSource")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("IPv4Region")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("IPv6Address")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("IPv6AddressSource")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("IPv6AsName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("IPv6Asn")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("IPv6City")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("IPv6CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("IPv6CountryName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("IPv6Isp")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("IPv6MetadataSource")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("IPv6Region")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double?>("JitterMs")
                        .HasColumnType("REAL");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LatencyMs")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("NetworkCheckedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NetworkIsStale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NetworkState")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("NetworkWarning")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double?>("PacketLossPercent")
                        .HasColumnType("REAL");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderMetadataJson")
                        .HasMaxLength(32768)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("QueuedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedServerId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultUrl")
                        .HasMaxLength(780)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerCountry")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerLocation")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double?>("UploadMbps")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.HasIndex("CompletedAtUtc", "Id")
                        .IsDescending();

                    b.HasIndex("ProviderId", "CompletedAtUtc", "Id")
                        .IsDescending(false, true, true);

                    b.HasIndex("Status", "CompletedAtUtc", "Id")
                        .IsDescending(false, true, true);

                    b.ToTable("SpeedTestResults", (string)null);
                });

            modelBuilder.Entity("SpeedtestDashboard.Infrastructure.Persistence.Entities.SpeedTestResultEntity", b =>
                {
                    b.HasOne("SpeedtestDashboard.Infrastructure.Persistence.Entities.SpeedTestJobEntity", "Job")
                        .WithOne("Result")
                        .HasForeignKey("SpeedtestDashboard.Infrastructure.Persistence.Entities.SpeedTestResultEntity", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SpeedtestDashboard.Infrastructure.Persistence.Entities.SpeedTestJobEntity", b =>
                {
                    b.Navigation("Result");
                });
#pragma warning restore 612, 618
        }
    }
}
