<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <InternalsVisibleTo Include="SpeedtestDashboard.Api.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpeedtestDashboard.Core\SpeedtestDashboard.Core.csproj" />
    <ProjectReference Include="..\SpeedtestDashboard.Infrastructure\SpeedtestDashboard.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifiers>linux-x64;linux-arm64;linux-musl-x64;linux-musl-arm64</RuntimeIdentifiers>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <FrontendDist Condition="'$(FrontendDist)' == ''">$(MSBuildProjectDirectory)/__frontend_not_supplied__</FrontendDist>
  </PropertyGroup>

  <ItemGroup Condition="Exists('$(FrontendDist)')">
    <Content Include="$(FrontendDist)/**/*" Link="wwwroot/%(RecursiveDir)%(Filename)%(Extension)" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Release'">
    <Content Update="appsettings.Development.json" CopyToPublishDirectory="Never" />
  </ItemGroup>

  <Target Name="EnsureWebRootExists" BeforeTargets="Build">
    <MakeDir Directories="$(MSBuildProjectDirectory)/wwwroot" />
  </Target>

</Project>
